### ISSUE TITLE
For frame [atom/camera]: Frame [atom/camera] does not exist

### ISSUE THREAD

**Issue by alam121** [harshmittal2210/Robotics_ws#12]
No camera feed or laser feed on rviz.

![1](https://user-images.githubusercontent.com/49236887/212824418-b1c0ed6b-5848-471d-85ee-a9709ff668b0.JPG)

**Comment by harshmittal2210** [comment]
![Screenshot from 2023-01-25 00-16-53](https://user-images.githubusercontent.com/31552243/214381526-0ff37d95-957e-400f-9b84-0a0a5f5e07a0.png)

I am able to see all the topics and data. Have you installed all the required libraries?

**Comment by LolfoollorS** [comment]
Hi, I have the same issue using melodic and I can see that the gazebo is publishing the data but not being accepted into rviz. I also have the issue of the robot not moving using the teleop sends the twist to the robot. (using rostopic it shows the x increasing but in gazebo it doesn't move at all.)

**Comment by harshmittal2210** [comment]
I am using noetic currently, I'll recommend you shift to Noetic as Melodic has EOL in May 2023. 

Still, I'll set up the same in melodic once I get the time. And try to replicate the issue.

**Comment by LolfoollorS** [comment]
Thanks. I have found that removing the robot name space in the .gazebo for both the lidar and camera fixed it.

**Comment by harshmittal2210** [comment]
Ohh that is great!

**Comment by Chandan-Srivatsa** [comment]
> Thanks. I have found that removing the robot name space in the .gazebo for both the lidar and camera fixes it.

when I did this I 
![Screenshot from 2023-07-01 12-36-16](https://github.com/harshmittal2210/Robotics_ws/assets/135217380/f4d2d502-3ff1-4671-b52b-35471426a3b5)
am getting this warning
