### ISSUE TITLE
I just have a question

### ISSUE THREAD

**Issue by InguChoi** [harshmittal2210/Robotics_ws#8]
Hi, thank you for making this project.
I have a question that can you try to make the SLAM(such as gmapping) package to Robotics_ws?

Thank you!

**Comment by harshmittal2210** [comment]
Sure will try to create one!

**Comment by harshmittal2210** [comment]
Hi @InguChoi I have added some gmapping related code in `develop` branch, soon when I have written and tested all the code I will merge it with the main branch.
